import { CatchUpAnalysis } from '../types';

export function generateMarkdownReport(analysis: CatchUpAnalysis): string {
  const { summary, priorities, decisions, actionItems, mentions, deadlines } = analysis;

  let md = `# 📋 Catch-Up Intelligence Briefing: "What Did I Miss?"\n`;
  md += `*Generated on: ${new Date().toLocaleString()} | Engine: ${analysis.processingEngine}*\n\n`;

  md += `## ⏱️ Executive Summary & Metrics\n`;
  md += `- **Reading Time Saved**: ~${summary.readingTimeSavedMinutes} minutes\n`;
  md += `- **Messages Analyzed**: ${summary.totalMessagesCount} messages across ${summary.participantCount} participants\n`;
  md += `- **Participants**: ${summary.participants.join(', ') || 'N/A'}\n\n`;
  md += `> ${summary.executiveOverview}\n\n`;

  if (summary.immediateAttentionItems.length > 0) {
    md += `### 🚨 Immediate Attention Needed:\n`;
    summary.immediateAttentionItems.forEach(item => {
      md += `- ${item}\n`;
    });
    md += `\n`;
  }

  if (summary.keyThemes.length > 0) {
    md += `### 💡 Key Highlights & Themes:\n`;
    summary.keyThemes.forEach(theme => {
      md += `- ${theme}\n`;
    });
    md += `\n`;
  }

  md += `## 🎯 Action Items & Next Steps (${actionItems.length})\n`;
  if (actionItems.length === 0) {
    md += `*No actionable tasks found in this conversation.*\n\n`;
  } else {
    actionItems.forEach((item, i) => {
      md += `${i + 1}. **[${item.priority}]** ${item.task}\n`;
      md += `   - **Owner**: ${item.owner}\n`;
      md += `   - **Due**: ${item.dueDate}\n`;
      md += `   - **Reason**: ${item.priorityReason}\n`;
      md += `   - *Source (${item.sourceSender})*: "${item.sourceExcerpt}"\n\n`;
    });
  }

  md += `## ⚖️ Decisions Made (${decisions.length})\n`;
  if (decisions.length === 0) {
    md += `*No explicit decisions recorded.*\n\n`;
  } else {
    decisions.forEach((dec, i) => {
      md += `${i + 1}. **[${dec.status}]** ${dec.decision}\n`;
      md += `   - *Source (${dec.sourceSender})*: "${dec.sourceExcerpt}"\n\n`;
    });
  }

  if (mentions.length > 0) {
    md += `## 🔔 Direct Mentions & Inquiries (${mentions.length})\n`;
    mentions.forEach((m, i) => {
      md += `${i + 1}. **From ${m.sourceSender}**: "${m.sourceExcerpt}"\n`;
      md += `   - Actionable: ${m.isActionable ? 'Yes ⚠️' : 'Informational'}\n\n`;
    });
  }

  if (deadlines.length > 0) {
    md += `## 📅 Deadlines & Key Dates (${deadlines.length})\n`;
    deadlines.forEach((d, i) => {
      md += `${i + 1}. **${d.dueDate}** — ${d.title} (Owner: ${d.owner})\n`;
    });
    md += `\n`;
  }

  md += `---\n*Generated by CatchUp AI — 100% Local-First Chat Intelligence*`;
  return md;
}

export function downloadTextFile(filename: string, content: string, contentType: string = 'text/plain') {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateIcsCalendar(analysis: CatchUpAnalysis): string {
  const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  let ics = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//CatchUp AI//What Did I Miss//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH'
  ];

  analysis.actionItems.forEach((item, index) => {
    if (item.dueDate && item.dueDate !== 'Not specified') {
      const uid = `catchup-task-${item.id}-${index}@catchup.ai`;
      ics.push('BEGIN:VEVENT');
      ics.push(`UID:${uid}`);
      ics.push(`DTSTAMP:${now}`);
      ics.push(`SUMMARY:Task: ${item.task.slice(0, 50)}`);
      ics.push(`DESCRIPTION:${item.task}\\nOwner: ${item.owner}\\nPriority: ${item.priority}\\nSource: ${item.sourceExcerpt}`);
      ics.push(`STATUS:CONFIRMED`);
      ics.push('END:VEVENT');
    }
  });

  ics.push('END:VCALENDAR');
  return ics.join('\r\n');
}
